### ISSUE TITLE
gAllowTrackClickToDrag=true not working in ScrollView

### ISSUE THREAD

**Issue by scratchboom** [qiujuer/Genius-Android#83]
net.qiujuer.genius:ui:2.0.0-beta7

Seems to be because of this
https://yadi.sk/i/8D6Xn3HatMBNV

**Comment by qiujuer** [comment]
Thank you very much for your question. Of course, this is actually done on purpose. Because the ScrollView layout in the priority response to the rolling event; at this time can only move to trigger it.
![90ef0e93-f47f-4399-b2c9-62f0f4d77700](https://cloud.githubusercontent.com/assets/5687320/16898606/4f734fc0-4c12-11e6-963d-c4d7ea717a12.png)
